<?php

namespace Tailor\Engine;

class Less
{

  private $source = '';
  private $filename = FALSE;

  private static $obj = NULL;

  public static $exts = array('less');

  public function __construct($source, $filename = FALSE)
  {
    $this->source   = $source;
    $this->filename = $filename;
  }

  public function render()
  {
    return static::parse($this->source, $this->filename);
  }

  public static function parse($text, $filename = 'unknown')
  {
    $ver  = \lessc::$VERSION;

    $out  = "/* Generated by LESS PHP $ver */\n\n";
    $out .= static::instance()->compile($text, $filename);

    return $out;
  }

  private static function instance()
  {
    if (static::$obj === NULL) {
      $css_dir = \Tailor\Config::get('styles_dir');
      $helpers = \Tailor\Helpers::functions();

      static::$obj = new \lessc;
      static::$obj->setImportDir($css_dir);

      foreach ($helpers as $name => $fn) {
        static::$obj->registerFunction($name, $fn);
      }
    }

    return static::$obj;
  }

}
